### ISSUE TITLE
Table will not add new row if you have an open input field while pressing the add row button

### ISSUE THREAD

**Issue by Benjadahl** [skille97/RAVI#4]
When you add a new row normally, or when you refresh the page it will be visible. 

It has something to do with the locking of the page refreshing when editing the input field.

Files to look out for:

/static/index.html
/static/index.js

**Comment by jbjjbjjbj** [comment]
Har fixed den, prøv at check

**Comment by RasmusRendal** [comment]
This has been fixed.
