### ISSUE TITLE
Database error in rightclick

### ISSUE THREAD

**Issue by jbjjbjjbj** [skille97/RAVI#6]
When giving some id cells a new color, it will lock the database and send out errors, when someone reloads the page. Only fix is to restart the program or wait, until database is unlocked.

Error is given by main.py

**Comment by Benjadahl** [comment]
I believe this might be caused by editing a cells context and colour at almost the same time. As this will open 2 database requests, but I am not sure.

**Comment by jbjjbjjbj** [comment]
But its only on some cells

**Comment by Benjadahl** [comment]
Fixed the issue by making sure that the client no longer makes invalid ajax requests.
